general/all_lo: $(general_OBJECTS)
include general/alloc_fac.d
include general/atom_handling.d
include general/atom_param.d
include general/avstruc.d
include general/calc_quatfit.d
include general/callback.d
include general/cluster_manager.d
include general/colouring.d
include general/coord_man.d
include general/correl.d
include general/data_structure.d
include general/defcell.d
include general/diagonalize.d
include general/edit_bond.d
include general/findhbonds.d
include general/findssbonds.d
include general/format.d
include general/input_gen.d
include general/iso_file_io.d
include general/ldp_control.d
include general/listener.d
include general/math_oper.d
include general/measure.d
include general/monitor.d
include general/msd.d
include general/nreg.d
include general/own_strtok.d
include general/plumber.d
include general/quatfit.d
include general/rdf.d
include general/sec_struct.d
include general/selections.d
include general/signal_handling.d
include general/spline.d
include general/stdafx.d
include general/trace_manager.d
include general/trajectory.d
include general/utility1.d
include general/utility2.d
include general/utility3.d
include general/utility4.d
include general/xasprintf.d
include general/xmath.d
include general/xprintf.d
include general/xscanf.d
include general/xtmpfile.d
graphics/all_lo: $(graphics_OBJECTS)
include graphics/g_Mmain.d
include graphics/g_Mmake.d
include graphics/g_clusterdriver.d
include graphics/g_coloring.d
include graphics/g_contdriver.d
include graphics/g_contour.d
include graphics/g_contplane.d
include graphics/g_font_manager.d
include graphics/g_hardcopy.d
include graphics/g_isocurve.d
include graphics/g_ldpdriver.d
include graphics/g_light_models.d
include graphics/g_main.d
include graphics/g_manipulate.d
include graphics/g_opengl_util.d
include graphics/g_output.d
include graphics/g_plot.d
include graphics/g_plot_cell.d
include graphics/g_plot_cluster.d
include graphics/g_plot_cpk.d
include graphics/g_plot_label.d
include graphics/g_plot_ldp.d
include graphics/g_plot_licorice.d
include graphics/g_plot_prop.d
include graphics/g_plot_stick.d
include graphics/g_plot_trace.d
include graphics/g_plotobj.d
include graphics/g_plumber.d
include graphics/g_quadstereo.d
include graphics/g_setup.d
include graphics/g_stereo.d
include graphics/g_surface_jpr.d
include graphics/g_tracedriver.d
include graphics/g_trajectory.d
include graphics/g_util.d
parser/all_lo: $(parser_OBJECTS)
include parser/p_atom.d
include parser/p_calculatec.d
include parser/p_center.d
include parser/p_contourc.d
include parser/p_copy.d
include parser/p_definec.d
include parser/p_diagonalize.d
include parser/p_display.d
include parser/p_editc.d
include parser/p_exportc.d
include parser/p_fillc.d
include parser/p_findc.d
include parser/p_hardcopyc.d
include parser/p_helpc.d
include parser/p_manipulatec.d
include parser/p_monitorc.d
include parser/p_openc.d
include parser/p_parser.d
include parser/p_plotc.d
include parser/p_plumberc.d
include parser/p_pythonc.d
include parser/p_read_fac.d
include parser/p_resetc.d
include parser/p_rotate.d
include parser/p_s_atomc.d
include parser/p_s_cellc.d
include parser/p_s_contourc.d
include parser/p_s_cutplanec.d
include parser/p_s_displaylistsc.d
include parser/p_s_gbasisc.d
include parser/p_s_lightc.d
include parser/p_s_materialc.d
include parser/p_s_monitorc.d
include parser/p_s_plumberc.d
include parser/p_s_windowc.d
include parser/p_savec.d
include parser/p_scalec.d
include parser/p_selectc.d
include parser/p_showc.d
include parser/p_tcl.d
include parser/p_tracec.d
include parser/p_trajparse.d
include parser/p_translatec.d
include parser/p_window.d
readwrite/all_lo: $(readwrite_OBJECTS)
include readwrite/rw_get_frame_amber.d
include readwrite/rw_get_frame_ambera.d
include readwrite/rw_get_frame_cerius2.d
include readwrite/rw_get_frame_charmm.d
include readwrite/rw_get_frame_discover.d
include readwrite/rw_get_frame_dl_poly.d
include readwrite/rw_get_frame_gromacs.d
include readwrite/rw_get_frame_gromos.d
include readwrite/rw_get_frame_gromos96a.d
include readwrite/rw_get_frame_hyper.d
include readwrite/rw_get_frame_mumod.d
include readwrite/rw_get_frame_tinker.d
include readwrite/rw_get_frame_xmol.d
include readwrite/rw_get_frame_xplor.d
include readwrite/rw_get_frame_yasp.d
include readwrite/rw_gotobmp.d
include readwrite/rw_gotosgi.d
include readwrite/rw_gototga.d
include readwrite/rw_gotoxwd.d
include readwrite/rw_ramber.d
include readwrite/rw_read_gbl_input.d
include readwrite/rw_read_model.d
include readwrite/rw_readdict.d
include readwrite/rw_rforce.d
include readwrite/rw_rgaussian.d
include readwrite/rw_rhyper.d
include readwrite/rw_rinsight.d
include readwrite/rw_rkarp.d
include readwrite/rw_rmol2.d
include readwrite/rw_rmopac.d
include readwrite/rw_rmumod.d
include readwrite/rw_ropenmol.d
include readwrite/rw_rpdb.d
include readwrite/rw_rxmol.d
include readwrite/rw_rxyz.d
include readwrite/rw_ryasp.d
include readwrite/rw_tocolps.d
include readwrite/rw_write_coord.d
include readwrite/rw_write_model.d
