C
C   This is a small program for transforming SYBYL ascii trajectory
C   files to AMBER binary ones
C
c   Compile and link:
c   f77 -o sybyl2amber sybyl2amber.f
c
C   Leif Laaksonen 1995
C
      parameter (MAXVEC = 30000)

      character*80 Infile,Outfile,label
      dimension   x(MAXVEC)

      write(6,*) 'Give input file name'
      read(5,'(A)') Infile
      write(6,*) 'Give output file name'
      read(5,'(A)') Outfile
      write(6,*) 'Give number of atoms'
      read(5,*) NumAtm

      open(unit=21,status="OLD",file=Infile,
     1 form="FORMATTED",ERR = 1001)

      open(unit=22,status="NEW",file=Outfile,
     1 form="UNFORMATTED",ERR = 1002)

      iframes = 0

      label = "Default label generated by SYBYL 2 Amber"
      write(6,*) 'Title: ',label
      write(22) label
      read(21,'(A)') label
5     continue
c
      read(21,*,end=2000) Time
      write(6,*) 'Processing frame at time: ',Time
      read(21,*,end=2001) (x(i),i = 1,3*Numatm)
      write(22) (x(i),i = 1,3*NumAtm)
      iframes = iframes + 1
      goto 5

1001  write(6,*) '?ERROR - in formatted file (can not open file)'
      stop
1002  write(6,*) '?ERROR - in unformatted file'
      stop
2000  write(6,*) '(break at time record) Found ',iframes,' frames'
      close(21)
      close(22)
      stop
2001  write(6,*) '(break at coordinate record) Found ',iframes,' frames'
      close(21)
      close(22)
      end









