##############################################################################
#                           Copyright (c) 2003 by:
#          Leif Laaksonen, CSC - Scientific Computing Ltd, ESPOO, FINLAND 
#                      Confidential unpublished property of 
#                              Leif Laaksonen   
#                            All rights reserved
#
#          Coded by: Eero Häkkinen
##############################################################################

# Retrieve object files in each specific directory.
# This file can be generated by `make objects' command.
include graphics/objects.mk

# Retrieve dependency rules.
# This file can be generated by `make depends' command.
include graphics/depends.mk

# Retrieve API dependencies.
# This file can be generated by `make gomapi' command.
include graphics/gomapi.mk
