/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you want to enable debugging code. */
/* #undef DEBUG */

/* Define if you want to enable API functions for extensions. */
#define ENABLE_EXTENSIONS 

/* Define to enable graphics sub system. */
#define ENABLE_GRAPHICS 

/* Produce a library (will produce a gom_main entry point). */
#define GOMLIB 

/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* Define to 1 if you have C99 [v][s[n]|f]printf. */
#define HAVE_C99_XPRINTF 

/* Define to 1 if you have C99 [v][s|f]scanf. */
#define HAVE_C99_XSCANF 

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `getrusage' function. */
#define HAVE_GETRUSAGE 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `gl' library (-lgl) and corresponding header
   files. */
#define HAVE_LIBGL 1

/* Define to 1 if you have the `glu' library (-lglu) and corresponding header
   files. */
#define HAVE_LIBGLU 1

/* Define to 1 if you have the `glut' library (-lglut) and corresponding
   header files. */
#define HAVE_LIBGLUT 1

/* Define to 1 if you have the `jpeg' library (-ljpeg) and corresponding
   header files. */
#define HAVE_LIBJPEG 1

/* Define to 1 if you have the `python' library (-lpython) and corresponding
   header files. */
#define HAVE_LIBPYTHON 1

/* Define to 1 if you have the `tcl' library (-ltcl) and corresponding header
   files. */
#define HAVE_LIBTCL 1

/* Define to 1 if you have the `tk' library (-ltk) and corresponding header
   files. */
#define HAVE_LIBTK 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `nearbyint' function. */
#define HAVE_NEARBYINT 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/procfs.h> header file. */
/* #undef HAVE_SYS_PROCFS_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vasprintf' function. */
#define HAVE_VASPRINTF 1

/* Define if you want to disable debugging code. */
#define NDEBUG 

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "gOpenMol"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "gOpenMol 3.00"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "gopenmol"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.00"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* The size of a `gom dummy sizeof *', as computed by sizeof. */
/* #undef SIZEOF_GOM_DUMMY_SIZEOF_P */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `intmax_t', as computed by sizeof. */
#define SIZEOF_INTMAX_T 8

/* The size of a `intptr_t', as computed by sizeof. */
#define SIZEOF_INTPTR_T 8

/* The size of a `long int', as computed by sizeof. */
#define SIZEOF_LONG_INT 8

/* The size of a `long long int', as computed by sizeof. */
#define SIZEOF_LONG_LONG_INT 8

/* The size of a `ptrdiff_t', as computed by sizeof. */
#define SIZEOF_PTRDIFF_T 8

/* The size of a `size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 8

/* The size of a `void *', as computed by sizeof. */
#define SIZEOF_VOID_P 8

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */
