extern int  gomp_Mmain(int, const char *[]);
extern int  gomp_StartUpStuff(int, const char *[]);
extern int  gomp_OpenStartFile(void);
extern int  gomp_OpenInputFiles(int, const char *[]);
extern int  gomp_SaveModuleName(const char *);
extern int  gomp_ResetgOpenMol(void);
extern int  gomp_RungOpenMolResetScript(void);
extern int  gomp_CommandLineInput(void);
extern void gomp_Exit(int);
extern int  gomp_PeekMessageQueue(void);
extern int  gomp_DefineSignals(void);
extern int  gomp_SetDisplayInterrupt(int);
extern int  gomp_GetDisplayInterrupt(void);
